name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fastapi-di-viz
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest --cov=fastapi_di_viz

      - name: Build package
        run: |
          poetry build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-di-viz
          path: dist/*

      - name: Publish package distributions to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
