name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest --cov=fastapi_di_viz

      - name: Build package
        run: |
          poetry build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-di-viz
          path: dist/*

      - name: Sanity check that version does not yet exist on PyPI
        if: github.ref == 'refs/heads/main'
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --dry-run

      - name: Upload package to PyPI with poetry
        if: github.ref == 'refs/heads/main'
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
